sudo: required
services:
    - docker
    - redis-server

language: node_js
node_js:
    - '12.4'

install: npm install

script: npm run test

env:
    matrix:
        - REDIS_HOST=localhost
          REDIS_DB=1
          REDIS_PORT=6379

jobs:
    include:
        - stage: mainnet
          script: npm run test --forceExit # Redis connection forces jest to remain open. --forceExit closes it.
          name: 'unit tests'
          env:
              - FACTOMD_HOST=api.factomd.net
                FACTOMD_PORT=443
                FACTOMD_PROTOCOL=https
        - script: npm run test-q -- --forceExit
          name: 'Query integreation tests'
        - stage: fds-mutation
          script: npm run test-m -- --forceExit
        - stage: fds-subscription
          script: npm run test-s -- --forceExit
