sudo: required
services:
    - docker
    - redis-server

language: node_js
node_js:
    - '12.4'

install: npm install

script: npm run test

aliases:
    redisio: &redis
        - REDIS_HOST=localhost
          REDIS_DB=1
          REDIS_PORT=6379
    mainnet: &mainnet
        - FACTOMD_HOST=api.factomd.net
          FACTOMD_PORT=443
          FACTOMD_PROTOCOL=https

jobs:
    include:
        - stage: mainnet
          script: npm run test
          name: 'Unit tests'
          env:
              - *mainnet
        - script: npm run test-q
          name: 'Query integreation tests'
          env:
              - *mainnet
        - script: npm run test-q
          name: 'Query integreation tests with Redis'
          env:
              - *redis
              - *mainnet
        - stage: fds-mutation
          script: npm run test-m
          name: 'Mutation integreation tests'
        - script: npm run test-m
          name: 'Mutation integreation tests with redis'
          env:
              - *redis
        - stage: fds-subscription
          script: npm run test-s
          name: 'Subscription integreation tests'
        - script: npm run test-s
          name: 'Subscription integreation tests with redis'
          env:
              - *redis
