sudo: required
services:
    - docker
language: node_js
node_js:
    - '12.4'

install: npm install

jobs:
    include: 
        - stage: mainnet # used for unit tests and query integration tests.
          script: npm run test
          script: npm run test-q
          env:
            FACTOMD_HOST=api.factomd.net
            FACTOMD_PORT=443
            FACTOMD_PROTOCOL=https
        # factom dev stack used for remaining tests
        - stage: fds-mutation 
          script: npm run test-m
        - stage: fds-subscription
          script: npm run test-s
